# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 445cd7406cde8570c85c38d643a6e4311ff938a6537e26dbd5a595e88cd207f7cc082494a279cd47727f6fa5c2693c241a8baee854969da504af60c45b9d2d01

test:
  secret_key_base: dca2d73c69dfa397f004f15ec3a343425a18fbc26a0eb511415df6da7c3c35a116105c7dc086f47970ee00fbbb52588c2958b0aad3c0a3d0fc09c5733df98b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
